# Generated by Django 5.1.2 on 2024-10-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acomodacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='acomodacao',
            name='local',
            field=models.CharField(default='assa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acomodacao',
            name='servicos',
            field=models.ManyToManyField(to='acomodacao.servico'),
        ),
    ]
