# Generated by Django 5.1.2 on 2024-10-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acomodacao', '0002_servico_acomodacao_local_acomodacao_servicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='quartos',
            field=models.ManyToManyField(to='acomodacao.acomodacaoquarto'),
        ),
    ]
